apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: phantom
bases:
  - ../../base
patches:
  - path: prod-patches.yaml
configMapGenerator:
  - name: phantom-config
    literals:
      - ENV=prod
      - LOG_LEVEL=info
      - PREDICTION_HORIZON=300
