apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: phantom
resources:
  - namespace.yaml
  - crd-predictivescaler.yaml
  - grafana.yaml
  - graph-builder.yaml
  - phantom-controller.yaml
  - phantom-ml.yaml
  - prometheus.yaml
  - otel-collector.yaml
