apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: phantom
  namespace: argocd
spec:
  generators:
  - list:
      elements:
      - env: dev
        namespace: phantom
        repoURL: https://github.com/phantom-io/phantom
        targetRevision: main
      - env: prod
        namespace: phantom
        repoURL: https://github.com/phantom-io/phantom
        targetRevision: release
  template:
    metadata:
      name: phantom-{{env}}
    spec:
      project: default
      source:
        repoURL: '{{repoURL}}'
        targetRevision: '{{targetRevision}}'
        path: kubernetes/overlays/{{env}}
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{namespace}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
        - CreateNamespace=true
        retry:
          limit: 5
          backoff:
            duration: 5s
            factor: 2
            maxDuration: 3m
